name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Triggers on any tag push

jobs:
  build:
    name: Build Terraform Provider with Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v2

        with:
          args: release --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build Docusaurus Documentation
        run: |
          npx create-docusaurus@latest "terraform provider otc-marketplace | Documentation" classic --typescript
          rm -rf "terraform provider otc-marketplace | Documentation"/docs
          mv docs "terraform provider otc-marketplace | Documentation"
          mv docusaurus.config.ts "terraform provider otc-marketplace | Documentation"
          cd "terraform provider otc-marketplace | Documentation"
          npm install
          npm install @docusaurus/plugin-client-redirects docusaurus-plugin-sass
          rm -rf src/pages/*
          terraform providers schema -json > schema.json
          python3 gen_docs.py
          npx docusaurus build
          mv build ../../public

      - name: Upload public artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public